# Generated by Django 5.2.12 on 2026-04-25 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('data_nascimento', models.DateField()),
                ('chave_pix', models.CharField(max_length=100)),
                ('qr_code_pix', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DespesaGeral',
            fields=[
                ('id_despesa_geral', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Moradia',
            fields=[
                ('id_moradia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('codigo_convite', models.CharField(max_length=50, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('rua', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DespesaDetalhe',
            fields=[
                ('id_despesa_detalhe', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('id_usuario_credor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('id_despesa_geral', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.despesageral')),
                ('id_moradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.moradia')),
            ],
        ),
        migrations.CreateModel(
            name='DespesaRateio',
            fields=[
                ('id_rateio', models.AutoField(primary_key=True, serialize=False)),
                ('valor_proporcional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_despesa_detalhe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.despesadetalhe')),
                ('id_usuario_devedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_moradia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.moradia'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('comprovante', models.CharField(max_length=255)),
                ('status_aprovacao', models.BooleanField(default=False)),
                ('id_rateio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.despesarateio')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id_tarefa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('data_limite', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('id_moradia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.moradia')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaResponsavel',
            fields=[
                ('id_tarefa_responsavel', models.AutoField(primary_key=True, serialize=False)),
                ('id_tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tarefa')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
