# Generated by Django 5.2.12 on 2026-04-26 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesageral',
            name='id_moradia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.moradia'),
        ),
    ]
