# Generated by Django 5.2.12 on 2026-04-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='qr_code_pix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
