# Generated by Django 5.2.12 on 2026-05-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_despesageral_id_moradia'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesadetalhe',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to='comprovantes/'),
        ),
    ]
